/*
 * Copyright PWF Technology LLC
 */
package com.pwf.ui.protohelper;

import com.pwf.mvc.ControllersManager;
import com.pwf.mvc.View;
import com.pwf.plugin.network.client.NetworkClientPlugin;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.plaf.basic.BasicComboBoxRenderer;

/**
 *
 * @author mfullen
 */
public class NetworkClientSelectionPanel extends javax.swing.JPanel implements
        View<Collection<NetworkClientPlugin>>
{
    private ControllersManager controllersManager = null;
    private Collection<NetworkClientPlugin> networkPlugins;

    @Override
    public void update(Collection<NetworkClientPlugin> networkPlugins)
    {
        this.networkPlugins = networkPlugins;
        List<NetworkClientPlugin> availableNetworkPlugins = new ArrayList<NetworkClientPlugin>(this.networkPlugins);
        NetworkClientPlugin[] toArray = availableNetworkPlugins.toArray(new NetworkClientPlugin[availableNetworkPlugins.size()]);
        DefaultComboBoxModel<NetworkClientPlugin> comboBoxModel = new DefaultComboBoxModel<NetworkClientPlugin>(toArray);

        this.networkSelectionCombobox.setModel(comboBoxModel);
    }

    @Override
    public String getName()
    {
        return "selectNetworkClient";
    }

    @Override
    public void setControllerManager(ControllersManager controllerManager)
    {
        this.controllersManager = controllerManager;
    }

    @Override
    public ControllersManager getControllerManager()
    {
        return this.controllersManager;
    }

    public NetworkClientPlugin getSelectedNetworkClientPlugin()
    {
        return (NetworkClientPlugin) this.networkSelectionCombobox.getSelectedItem();
    }

    /**
     * Creates new form NetworkClientSelectionPanel
     */
    public NetworkClientSelectionPanel()
    {
        initComponents();
        this.networkSelectionCombobox.setRenderer(new BasicComboBoxRenderer()
        {
            @Override
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus)
            {
                JLabel render = (JLabel) super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                String text = "";
                if (value == null)
                {

                    text = "No Network Plugins available.";
                }
                else if (value instanceof NetworkClientPlugin)
                {
                    NetworkClientPlugin p = (NetworkClientPlugin) value;
                    text = String.format("%s", p.getPluginInformation().getName());
                }
                render.setText(text);
                return render;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        networkSelectionCombobox = new javax.swing.JComboBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nework Plugin Selection", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(10, 36, 106)));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 5, 0};
        layout.rowHeights = new int[] {0};
        setLayout(layout);

        jLabel1.setText("Networking Plugin:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(38, 40, 0, 0);
        add(jLabel1, gridBagConstraints);

        networkSelectionCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 165;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(38, 39, 33, 10);
        add(networkSelectionCombobox, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox networkSelectionCombobox;
    // End of variables declaration//GEN-END:variables
}
